// Mock data and API functions for CuraLink

export interface Expert {
  id: string;
  name: string;
  specialization: string;
  institution: string;
  country: string;
  tags: string[];
  photo: string;
  match: number;
  isFollowing?: boolean;
}

export interface ClinicalTrial {
  id: string;
  title: string;
  phase: string;
  status: string;
  description: string;
  location: string;
  summary: string;
  tags: string[];
  isSaved?: boolean;
}

export interface Publication {
  id: string;
  title: string;
  authors: string[];
  abstract: string;
  summary: string;
  tags: string[];
  year: number;
  isSaved?: boolean;
}

export interface ForumPost {
  id: string;
  title: string;
  category: string;
  content: string;
  author: string;
  tags: string[];
  replies: number;
  views: number;
  timestamp: Date;
}

// Mock Experts Data
export const mockExperts: Expert[] = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    specialization: "Oncology & Immunotherapy",
    institution: "Memorial Sloan Kettering Cancer Center",
    country: "United States",
    tags: ["Cancer Research", "Immunotherapy", "Clinical Trials"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 95,
  },
  {
    id: "2",
    name: "Prof. Michael Anderson",
    specialization: "Cardiovascular Disease",
    institution: "Mayo Clinic",
    country: "United States",
    tags: ["Cardiology", "Heart Disease", "Prevention"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 92,
  },
  {
    id: "3",
    name: "Dr. Yuki Tanaka",
    specialization: "Neurodegenerative Diseases",
    institution: "University of Tokyo",
    country: "Japan",
    tags: ["Alzheimer's", "Parkinson's", "Neurology"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 90,
  },
  {
    id: "4",
    name: "Dr. Maria Rodriguez",
    specialization: "Rare Genetic Disorders",
    institution: "Hospital Universitario La Paz",
    country: "Spain",
    tags: ["Genetics", "Rare Diseases", "Pediatrics"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 88,
  },
  {
    id: "5",
    name: "Prof. David Kim",
    specialization: "Diabetes & Metabolic Disorders",
    institution: "Seoul National University Hospital",
    country: "South Korea",
    tags: ["Diabetes", "Metabolism", "Endocrinology"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 87,
  },
  {
    id: "6",
    name: "Dr. Emma Williams",
    specialization: "Infectious Diseases",
    institution: "London School of Hygiene",
    country: "United Kingdom",
    tags: ["Virology", "Epidemiology", "Public Health"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 85,
  },
  {
    id: "7",
    name: "Prof. Ahmed Hassan",
    specialization: "Cancer Genomics",
    institution: "King Faisal Specialist Hospital",
    country: "Saudi Arabia",
    tags: ["Genomics", "Precision Medicine", "Cancer"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 84,
  },
  {
    id: "8",
    name: "Dr. Lisa Müller",
    specialization: "Autoimmune Diseases",
    institution: "Charité University Hospital",
    country: "Germany",
    tags: ["Rheumatology", "Autoimmune", "Immunology"],
    photo: "https://images.unsplash.com/photo-1588731234159-8b630409b0f8?w=400",
    match: 83,
  },
  {
    id: "9",
    name: "Dr. Raj Patel",
    specialization: "Stem Cell Therapy",
    institution: "All India Institute of Medical Sciences",
    country: "India",
    tags: ["Stem Cells", "Regenerative Medicine", "Research"],
    photo: "https://images.unsplash.com/photo-1618498082410-b4aa22193b38?w=400",
    match: 82,
  },
  {
    id: "10",
    name: "Prof. Sophie Dubois",
    specialization: "Pediatric Oncology",
    institution: "Institut Curie",
    country: "France",
    tags: ["Pediatrics", "Cancer", "Clinical Research"],
    photo: "https://images.unsplash.com/photo-1614608682850-2f026e6a3c67?w=400",
    match: 81,
  },
  {
    id: "11",
    name: "Dr. James O'Connor",
    specialization: "Neurosurgery & Brain Tumors",
    institution: "Johns Hopkins Hospital",
    country: "United States",
    tags: ["Neurosurgery", "Brain Cancer", "Clinical Trials"],
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400",
    match: 94,
  },
  {
    id: "12",
    name: "Prof. Elena Petrova",
    specialization: "Hematology & Blood Disorders",
    institution: "Moscow Institute of Hematology",
    country: "Russia",
    tags: ["Hematology", "Leukemia", "Bone Marrow"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 89,
  },
  {
    id: "13",
    name: "Dr. Carlos Mendes",
    specialization: "Tropical Medicine & Infectious Disease",
    institution: "University of São Paulo",
    country: "Brazil",
    tags: ["Tropical Medicine", "Infectious Disease", "Public Health"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 86,
  },
  {
    id: "14",
    name: "Dr. Fatima Al-Rashid",
    specialization: "Maternal-Fetal Medicine",
    institution: "Dubai Healthcare City",
    country: "UAE",
    tags: ["Obstetrics", "High-Risk Pregnancy", "Fetal Medicine"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 84,
  },
  {
    id: "15",
    name: "Prof. Hans Schmidt",
    specialization: "Organ Transplantation",
    institution: "University Hospital Zurich",
    country: "Switzerland",
    tags: ["Transplant Surgery", "Immunosuppression", "Organ Donation"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 93,
  },
  {
    id: "16",
    name: "Dr. Priya Sharma",
    specialization: "Genetic Counseling & Testing",
    institution: "Tata Memorial Centre",
    country: "India",
    tags: ["Genetics", "Counseling", "Cancer Predisposition"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 87,
  },
  {
    id: "17",
    name: "Dr. Robert Zhang",
    specialization: "Pulmonology & Lung Cancer",
    institution: "Shanghai Chest Hospital",
    country: "China",
    tags: ["Pulmonology", "Lung Cancer", "Thoracic Surgery"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 91,
  },
  {
    id: "18",
    name: "Prof. Isabella Romano",
    specialization: "Dermatology & Melanoma",
    institution: "University of Milan",
    country: "Italy",
    tags: ["Dermatology", "Skin Cancer", "Melanoma"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 88,
  },
  {
    id: "19",
    name: "Dr. Thomas van der Berg",
    specialization: "Pediatric Neurology",
    institution: "Amsterdam Medical Center",
    country: "Netherlands",
    tags: ["Pediatrics", "Neurology", "Epilepsy"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 85,
  },
  {
    id: "20",
    name: "Dr. Aisha Nkomo",
    specialization: "HIV/AIDS Research",
    institution: "University of Cape Town",
    country: "South Africa",
    tags: ["HIV", "AIDS", "Infectious Disease"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 90,
  },
  {
    id: "21",
    name: "Prof. Dimitri Volkov",
    specialization: "Gastrointestinal Oncology",
    institution: "Petrov Research Institute",
    country: "Russia",
    tags: ["GI Cancer", "Colorectal", "Pancreatic"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 89,
  },
  {
    id: "22",
    name: "Dr. Jennifer Park",
    specialization: "Breast Cancer & Women's Health",
    institution: "Stanford Medical Center",
    country: "United States",
    tags: ["Breast Cancer", "Women's Health", "Oncology"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 92,
  },
  {
    id: "23",
    name: "Dr. Omar Khalil",
    specialization: "Pediatric Surgery",
    institution: "Cairo University Hospital",
    country: "Egypt",
    tags: ["Pediatric Surgery", "Congenital Disorders", "Neonatal"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 83,
  },
  {
    id: "24",
    name: "Prof. Anna Kowalski",
    specialization: "Radiation Oncology",
    institution: "Marie Curie Institute",
    country: "Poland",
    tags: ["Radiation Therapy", "Cancer Treatment", "Clinical Trials"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 88,
  },
  {
    id: "25",
    name: "Dr. Ricardo Silva",
    specialization: "Nephrology & Kidney Disease",
    institution: "Hospital das Clínicas",
    country: "Portugal",
    tags: ["Nephrology", "Dialysis", "Kidney Transplant"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 86,
  },
  {
    id: "26",
    name: "Dr. Kenji Yamamoto",
    specialization: "Regenerative Medicine",
    institution: "Kyoto University Hospital",
    country: "Japan",
    tags: ["Regenerative Medicine", "Stem Cells", "Tissue Engineering"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 91,
  },
  {
    id: "27",
    name: "Prof. Margaret O'Brien",
    specialization: "Palliative Care & Pain Management",
    institution: "Trinity College Dublin",
    country: "Ireland",
    tags: ["Palliative Care", "Pain Management", "End-of-Life"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 82,
  },
  {
    id: "28",
    name: "Dr. Felipe Gonzalez",
    specialization: "Endocrinology & Thyroid Disorders",
    institution: "Hospital Clinic Barcelona",
    country: "Spain",
    tags: ["Endocrinology", "Thyroid", "Hormones"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 84,
  },
  {
    id: "29",
    name: "Dr. Nadia Hassan",
    specialization: "Mental Health & Oncology",
    institution: "American University of Beirut",
    country: "Lebanon",
    tags: ["Psycho-Oncology", "Mental Health", "Patient Support"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 80,
  },
  {
    id: "30",
    name: "Prof. Lars Andersen",
    specialization: "Cardiac Surgery",
    institution: "Karolinska Institute",
    country: "Sweden",
    tags: ["Cardiac Surgery", "Heart Transplant", "Valve Repair"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 93,
  },
  {
    id: "31",
    name: "Dr. Mei Lin",
    specialization: "Gynecologic Oncology",
    institution: "National Taiwan University Hospital",
    country: "Taiwan",
    tags: ["Gynecology", "Ovarian Cancer", "Cervical Cancer"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 87,
  },
  {
    id: "32",
    name: "Dr. Ibrahim Osman",
    specialization: "Orthopedic Oncology",
    institution: "King Abdulaziz Medical City",
    country: "Saudi Arabia",
    tags: ["Orthopedics", "Bone Cancer", "Sarcoma"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 85,
  },
  {
    id: "33",
    name: "Prof. Claire Beaumont",
    specialization: "Clinical Pharmacology",
    institution: "University of Montreal",
    country: "Canada",
    tags: ["Pharmacology", "Drug Development", "Clinical Trials"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 89,
  },
  {
    id: "34",
    name: "Dr. Anastasia Ivanova",
    specialization: "Molecular Pathology",
    institution: "Russian Cancer Research Center",
    country: "Russia",
    tags: ["Pathology", "Molecular Diagnostics", "Biomarkers"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 86,
  },
  {
    id: "35",
    name: "Dr. Marcus Johnson",
    specialization: "Urologic Oncology",
    institution: "MD Anderson Cancer Center",
    country: "United States",
    tags: ["Urology", "Prostate Cancer", "Bladder Cancer"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 91,
  },
  {
    id: "36",
    name: "Dr. Leila Mansouri",
    specialization: "Nuclear Medicine",
    institution: "Tehran University of Medical Sciences",
    country: "Iran",
    tags: ["Nuclear Medicine", "PET Imaging", "Radiotherapy"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 84,
  },
  {
    id: "37",
    name: "Prof. Wolfgang Bauer",
    specialization: "Medical Oncology",
    institution: "University Hospital Heidelberg",
    country: "Germany",
    tags: ["Medical Oncology", "Targeted Therapy", "Precision Medicine"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 92,
  },
  {
    id: "38",
    name: "Dr. Soo-Jin Lee",
    specialization: "Head & Neck Surgery",
    institution: "Asan Medical Center",
    country: "South Korea",
    tags: ["ENT", "Head and Neck Cancer", "Reconstructive Surgery"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 88,
  },
  {
    id: "39",
    name: "Dr. Antonio Ferrara",
    specialization: "Gastrointestinal Surgery",
    institution: "University of Naples",
    country: "Italy",
    tags: ["GI Surgery", "Liver", "Pancreatic Surgery"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 87,
  },
  {
    id: "40",
    name: "Dr. Rachel Cohen",
    specialization: "Pediatric Hematology",
    institution: "Boston Children's Hospital",
    country: "United States",
    tags: ["Pediatrics", "Hematology", "Leukemia"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 90,
  },
  {
    id: "41",
    name: "Prof. Jun Wei",
    specialization: "Hepatobiliary Surgery",
    institution: "Peking Union Medical College",
    country: "China",
    tags: ["Liver Cancer", "Hepatobiliary", "Transplant"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 89,
  },
  {
    id: "42",
    name: "Dr. Amina Bakr",
    specialization: "Reproductive Medicine",
    institution: "Alexandria Medical School",
    country: "Egypt",
    tags: ["Reproductive Health", "Fertility", "IVF"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 83,
  },
  {
    id: "43",
    name: "Dr. Pierre Lefebvre",
    specialization: "Thoracic Surgery",
    institution: "Gustave Roussy Institute",
    country: "France",
    tags: ["Thoracic Surgery", "Lung Cancer", "Esophageal"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 91,
  },
  {
    id: "44",
    name: "Dr. Rajesh Kumar",
    specialization: "Interventional Radiology",
    institution: "AIIMS New Delhi",
    country: "India",
    tags: ["Interventional Radiology", "Minimally Invasive", "Tumor Ablation"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 86,
  },
  {
    id: "45",
    name: "Prof. Ingrid Svensson",
    specialization: "Clinical Genetics",
    institution: "Uppsala University Hospital",
    country: "Sweden",
    tags: ["Clinical Genetics", "Hereditary Cancer", "Genetic Testing"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 88,
  },
  {
    id: "46",
    name: "Dr. Hassan Mahmoud",
    specialization: "Medical Physics",
    institution: "King Hussein Cancer Center",
    country: "Jordan",
    tags: ["Medical Physics", "Radiation Therapy", "Dosimetry"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 82,
  },
  {
    id: "47",
    name: "Dr. Victoria Chang",
    specialization: "Neuro-Oncology",
    institution: "Singapore General Hospital",
    country: "Singapore",
    tags: ["Neuro-Oncology", "Brain Tumors", "Glioblastoma"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 93,
  },
  {
    id: "48",
    name: "Prof. Javier Morales",
    specialization: "Surgical Oncology",
    institution: "Instituto Nacional de Cancerología",
    country: "Mexico",
    tags: ["Surgical Oncology", "Cancer Surgery", "Minimally Invasive"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 90,
  },
  {
    id: "49",
    name: "Dr. Zara Khan",
    specialization: "Pediatric Oncology",
    institution: "Aga Khan University Hospital",
    country: "Pakistan",
    tags: ["Pediatric Oncology", "Childhood Cancer", "Leukemia"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 87,
  },
  {
    id: "50",
    name: "Dr. Henrik Nielsen",
    specialization: "Oncology Nursing Research",
    institution: "University of Copenhagen",
    country: "Denmark",
    tags: ["Nursing Research", "Patient Care", "Quality of Life"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 81,
  },
  {
    id: "51",
    name: "Prof. Gabriela Santos",
    specialization: "Cancer Epidemiology",
    institution: "University of Lisbon",
    country: "Portugal",
    tags: ["Epidemiology", "Cancer Prevention", "Population Health"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 85,
  },
  {
    id: "52",
    name: "Dr. Alexei Petrov",
    specialization: "Sarcoma & Bone Cancer",
    institution: "Blokhin Cancer Research Center",
    country: "Russia",
    tags: ["Sarcoma", "Bone Cancer", "Soft Tissue Tumors"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 89,
  },
  {
    id: "53",
    name: "Dr. Samantha Wright",
    specialization: "Cancer Rehabilitation",
    institution: "Royal Marsden Hospital",
    country: "United Kingdom",
    tags: ["Rehabilitation", "Physical Therapy", "Survivorship"],
    photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400",
    match: 80,
  },
  {
    id: "54",
    name: "Prof. Kwang-Ho Lee",
    specialization: "Cancer Biomarkers",
    institution: "Samsung Medical Center",
    country: "South Korea",
    tags: ["Biomarkers", "Liquid Biopsy", "Early Detection"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 92,
  },
  {
    id: "55",
    name: "Dr. Francesca Bianchi",
    specialization: "Cancer Nutrition",
    institution: "European Institute of Oncology",
    country: "Italy",
    tags: ["Nutrition", "Diet", "Cancer Prevention"],
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    match: 82,
  },
  {
    id: "56",
    name: "Dr. Ahmed El-Sayed",
    specialization: "Pediatric Neuro-Oncology",
    institution: "Children's Cancer Hospital",
    country: "Egypt",
    tags: ["Pediatric Neuro-Oncology", "Brain Tumors", "Children"],
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400",
    match: 88,
  },
  {
    id: "57",
    name: "Prof. Marina Popescu",
    specialization: "Cancer Survivorship",
    institution: "Bucharest Oncology Institute",
    country: "Romania",
    tags: ["Survivorship", "Long-term Effects", "Quality of Life"],
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
    match: 81,
  },
  {
    id: "58",
    name: "Dr. Takeshi Nakamura",
    specialization: "Cancer Immunology",
    institution: "Osaka University Hospital",
    country: "Japan",
    tags: ["Immunology", "Cancer Vaccines", "T-Cell Therapy"],
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400",
    match: 94,
  },
  {
    id: "59",
    name: "Dr. Sofia Ramirez",
    specialization: "Breast Reconstruction",
    institution: "Hospital de Clínicas",
    country: "Argentina",
    tags: ["Plastic Surgery", "Breast Reconstruction", "Post-Cancer"],
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    match: 83,
  },
  {
    id: "60",
    name: "Prof. Nathan Green",
    specialization: "Cancer Health Economics",
    institution: "University of Toronto",
    country: "Canada",
    tags: ["Health Economics", "Cost-Effectiveness", "Policy"],
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400",
    match: 79,
  },
];

// Mock Clinical Trials Data
export const mockTrials: ClinicalTrial[] = [
  {
    id: "trial-1",
    title: "Phase III Study of Novel Immunotherapy for Advanced Melanoma",
    phase: "Phase III",
    status: "Recruiting",
    description: "A randomized, double-blind, placebo-controlled trial evaluating the efficacy and safety of a novel checkpoint inhibitor combination in patients with advanced melanoma who have progressed on standard therapy.",
    location: "Multiple sites across US, EU, and Asia",
    summary: "This trial tests a new combination of drugs that help the immune system fight melanoma cancer cells.",
    tags: ["Melanoma", "Immunotherapy", "Oncology"],
  },
  {
    id: "trial-2",
    title: "Gene Therapy for Sickle Cell Disease - Long-term Follow-up",
    phase: "Phase II",
    status: "Active",
    description: "A long-term follow-up study of patients who received CRISPR-based gene therapy for sickle cell disease, monitoring safety, efficacy, and quality of life outcomes.",
    location: "Boston, San Francisco, London",
    summary: "Following patients who received gene editing treatment to see if it continues to help with sickle cell disease.",
    tags: ["Gene Therapy", "CRISPR", "Sickle Cell"],
  },
  {
    id: "trial-3",
    title: "Alzheimer's Disease Prevention Trial in High-Risk Individuals",
    phase: "Phase II",
    status: "Recruiting",
    description: "A prevention trial testing whether an investigational drug can delay the onset of Alzheimer's disease in cognitively normal individuals with genetic risk factors.",
    location: "Academic medical centers worldwide",
    summary: "Testing if a new drug can prevent or delay Alzheimer's in people at high risk.",
    tags: ["Alzheimer's", "Prevention", "Neurology"],
  },
  {
    id: "trial-4",
    title: "CAR-T Cell Therapy for Refractory Multiple Myeloma",
    phase: "Phase I/II",
    status: "Recruiting",
    description: "Evaluating the safety and preliminary efficacy of BCMA-targeted CAR-T cell therapy in patients with relapsed/refractory multiple myeloma.",
    location: "Major cancer centers in North America",
    summary: "Using modified immune cells to attack multiple myeloma cancer that hasn't responded to other treatments.",
    tags: ["CAR-T", "Multiple Myeloma", "Cell Therapy"],
  },
  {
    id: "trial-5",
    title: "Digital Therapeutics for Type 2 Diabetes Management",
    phase: "Phase III",
    status: "Active",
    description: "A pragmatic trial testing an AI-powered digital therapeutic platform for improving glycemic control and medication adherence in type 2 diabetes patients.",
    location: "Conducted remotely - International",
    summary: "Testing if an app with AI coaching can help people manage their diabetes better.",
    tags: ["Diabetes", "Digital Health", "AI"],
  },
  {
    id: "trial-6",
    title: "Personalized Vaccine for Pancreatic Cancer",
    phase: "Phase I",
    status: "Recruiting",
    description: "First-in-human study of a personalized mRNA vaccine targeting patient-specific tumor mutations in pancreatic ductal adenocarcinoma.",
    location: "Memorial Sloan Kettering, Dana-Farber",
    summary: "Testing personalized vaccines made from each patient's tumor to fight pancreatic cancer.",
    tags: ["Pancreatic Cancer", "mRNA Vaccine", "Personalized Medicine"],
  },
  {
    id: "trial-7",
    title: "Liquid Biopsy for Early Detection of Colorectal Cancer",
    phase: "Phase III",
    status: "Active",
    description: "Large-scale validation study of a blood-based screening test for early detection of colorectal cancer in average-risk populations.",
    location: "Multi-center across US, Canada, Europe",
    summary: "Testing if a simple blood test can detect colon cancer early before symptoms appear.",
    tags: ["Colorectal Cancer", "Early Detection", "Liquid Biopsy"],
  },
  {
    id: "trial-8",
    title: "Targeted Therapy for HER2-Positive Gastric Cancer",
    phase: "Phase II",
    status: "Recruiting",
    description: "Evaluating a novel antibody-drug conjugate in patients with HER2-positive advanced gastric or gastroesophageal junction cancer.",
    location: "Asia-Pacific region, 50+ centers",
    summary: "Testing a new targeted drug that delivers chemotherapy directly to HER2-positive stomach cancer cells.",
    tags: ["Gastric Cancer", "HER2", "Targeted Therapy"],
  },
  {
    id: "trial-9",
    title: "Microbiome Modulation in Melanoma Immunotherapy",
    phase: "Phase II",
    status: "Recruiting",
    description: "Investigating whether gut microbiome modification through fecal microbiota transplant can improve response to checkpoint inhibitors in melanoma.",
    location: "MD Anderson, NIH Clinical Center",
    summary: "Testing if changing gut bacteria can help immunotherapy work better against melanoma.",
    tags: ["Melanoma", "Microbiome", "Immunotherapy"],
  },
  {
    id: "trial-10",
    title: "AI-Guided Radiation Therapy for Prostate Cancer",
    phase: "Phase III",
    status: "Active",
    description: "Randomized trial comparing AI-optimized adaptive radiation therapy versus standard radiation for localized prostate cancer.",
    location: "Academic radiation oncology centers worldwide",
    summary: "Using artificial intelligence to personalize radiation treatment for prostate cancer.",
    tags: ["Prostate Cancer", "Radiation", "AI"],
  },
  {
    id: "trial-11",
    title: "Oncolytic Virus Therapy for Glioblastoma",
    phase: "Phase I/II",
    status: "Recruiting",
    description: "Safety and efficacy study of intratumoral injection of modified oncolytic virus in recurrent glioblastoma multiforme.",
    location: "Duke, UCSF, Johns Hopkins",
    summary: "Testing if engineered viruses that infect and kill cancer cells can treat aggressive brain tumors.",
    tags: ["Glioblastoma", "Oncolytic Virus", "Brain Cancer"],
  },
  {
    id: "trial-12",
    title: "Exercise Intervention During Chemotherapy",
    phase: "Phase II",
    status: "Active",
    description: "Evaluating impact of structured exercise program on treatment tolerance, outcomes, and quality of life in patients receiving chemotherapy for breast cancer.",
    location: "Community oncology practices nationwide",
    summary: "Studying if exercise during chemotherapy helps patients feel better and improves outcomes.",
    tags: ["Breast Cancer", "Exercise", "Quality of Life"],
  },
  {
    id: "trial-13",
    title: "Combination Immunotherapy for Non-Small Cell Lung Cancer",
    phase: "Phase III",
    status: "Recruiting",
    description: "Comparing dual checkpoint inhibition versus single agent in first-line treatment of advanced NSCLC without driver mutations.",
    location: "International, 200+ sites",
    summary: "Testing if combining two immunotherapy drugs works better than one for lung cancer.",
    tags: ["Lung Cancer", "Immunotherapy", "Checkpoint Inhibitors"],
  },
  {
    id: "trial-14",
    title: "Circulating Tumor DNA Monitoring After Surgery",
    phase: "Phase II",
    status: "Active",
    description: "Using ctDNA testing to detect minimal residual disease and guide adjuvant therapy decisions in stage II-III colorectal cancer.",
    location: "Mayo Clinic network",
    summary: "Testing if blood tests after surgery can guide decisions about additional treatment.",
    tags: ["Colorectal Cancer", "ctDNA", "Precision Medicine"],
  },
  {
    id: "trial-15",
    title: "PARP Inhibitor for Ovarian Cancer Maintenance",
    phase: "Phase III",
    status: "Active",
    description: "Evaluating maintenance therapy with PARP inhibitor in patients with newly diagnosed advanced ovarian cancer responding to platinum-based chemotherapy.",
    location: "GOG sites across North America",
    summary: "Testing if maintenance therapy after chemotherapy can prevent ovarian cancer from coming back.",
    tags: ["Ovarian Cancer", "PARP Inhibitor", "Maintenance Therapy"],
  },
  {
    id: "trial-16",
    title: "Cryoablation for Early-Stage Breast Cancer",
    phase: "Phase II",
    status: "Recruiting",
    description: "Single-arm study of image-guided cryoablation as an alternative to surgery for small, low-risk breast cancers in older women.",
    location: "Select academic medical centers",
    summary: "Testing if freezing small breast tumors can be an alternative to surgery.",
    tags: ["Breast Cancer", "Cryoablation", "Minimally Invasive"],
  },
  {
    id: "trial-17",
    title: "Aspirin for Cancer Prevention in Lynch Syndrome",
    phase: "Phase III",
    status: "Active",
    description: "Long-term follow-up of daily aspirin use for prevention of colorectal and other cancers in individuals with Lynch syndrome.",
    location: "International Lynch syndrome registries",
    summary: "Studying if daily aspirin can prevent cancer in people with inherited cancer risk.",
    tags: ["Prevention", "Lynch Syndrome", "Aspirin"],
  },
  {
    id: "trial-18",
    title: "Neoadjuvant Immunotherapy for Bladder Cancer",
    phase: "Phase II",
    status: "Recruiting",
    description: "Testing checkpoint inhibitor therapy before surgery (neoadjuvant) in muscle-invasive bladder cancer to improve surgical outcomes.",
    location: "NCI-designated cancer centers",
    summary: "Giving immunotherapy before surgery to improve outcomes in bladder cancer.",
    tags: ["Bladder Cancer", "Neoadjuvant", "Immunotherapy"],
  },
  {
    id: "trial-19",
    title: "Targeted Alpha Therapy for Metastatic Prostate Cancer",
    phase: "Phase III",
    status: "Recruiting",
    description: "Evaluating radium-223 dichloride in combination with standard therapy for metastatic castration-resistant prostate cancer with bone metastases.",
    location: "Europe and North America",
    summary: "Testing radioactive treatment that targets prostate cancer spread to bones.",
    tags: ["Prostate Cancer", "Radiopharmaceutical", "Bone Metastases"],
  },
  {
    id: "trial-20",
    title: "Window-of-Opportunity Trial in Triple Negative Breast Cancer",
    phase: "Phase II",
    status: "Recruiting",
    description: "Short-term pre-surgical treatment with novel immunotherapy combination to assess biological response and identify predictive biomarkers.",
    location: "Breast cancer specialty centers",
    summary: "Testing new immunotherapy drugs in the weeks before surgery to see how tumors respond.",
    tags: ["Breast Cancer", "Triple Negative", "Window Trial"],
  },
];

// Mock Publications Data
export const mockPublications: Publication[] = [
  {
    id: "pub-1",
    title: "CRISPR-Cas9 Gene Editing: Mechanisms, Applications, and Clinical Prospects",
    authors: ["Zhang, F.", "Doudna, J.A.", "Charpentier, E."],
    abstract: "CRISPR-Cas9 has revolutionized genome editing with its precision and versatility. This review examines the molecular mechanisms underlying CRISPR-Cas9 function, discusses current applications in basic research and therapeutic development, and explores the prospects and challenges for clinical translation.",
    summary: "A comprehensive review of how CRISPR gene editing works and its potential medical uses.",
    tags: ["CRISPR", "Gene Editing", "Molecular Biology"],
    year: 2024,
  },
  {
    id: "pub-2",
    title: "Immunotherapy Combinations in Advanced Cancer: Synergy and Resistance Mechanisms",
    authors: ["Chen, D.S.", "Mellman, I.", "Wolchok, J.D."],
    abstract: "Combination immunotherapy strategies have shown remarkable efficacy in various cancers. This article explores the biological rationale for different combination approaches, mechanisms of synergy, patterns of resistance, and biomarkers for patient selection.",
    summary: "Explains how combining different immunotherapy drugs can work better against cancer.",
    tags: ["Immunotherapy", "Cancer", "Oncology"],
    year: 2024,
  },
  {
    id: "pub-3",
    title: "Artificial Intelligence in Medical Diagnosis: Current Capabilities and Future Directions",
    authors: ["Topol, E.J.", "Rajpurkar, P.", "Lungren, M.P."],
    abstract: "AI and deep learning have achieved human-level performance in various diagnostic tasks. This review assesses current AI applications in radiology, pathology, and clinical decision support, discusses limitations and bias concerns, and projects future developments.",
    summary: "Reviews how AI is being used to help doctors diagnose diseases and what's coming next.",
    tags: ["AI", "Diagnostics", "Machine Learning"],
    year: 2024,
  },
  {
    id: "pub-4",
    title: "The Microbiome-Gut-Brain Axis in Neurological Disorders",
    authors: ["Cryan, J.F.", "Dinan, T.G.", "Mayer, E.A."],
    abstract: "Emerging evidence suggests bidirectional communication between gut microbiota and the central nervous system. This article reviews the role of the microbiome in neurodevelopmental and neurodegenerative disorders and discusses therapeutic implications.",
    summary: "How bacteria in your gut might affect brain health and diseases like Parkinson's and Alzheimer's.",
    tags: ["Microbiome", "Neuroscience", "Gut-Brain Axis"],
    year: 2023,
  },
  {
    id: "pub-5",
    title: "Precision Medicine in Cardiovascular Disease: Genomics, Biomarkers, and Personalized Treatment",
    authors: ["Anderson, K.M.", "Mehta, L.S.", "Shah, R.V."],
    abstract: "Cardiovascular disease remains the leading cause of mortality worldwide. This review examines how genomic profiling, novel biomarkers, and advanced imaging are enabling personalized risk stratification and targeted therapies in cardiovascular medicine.",
    summary: "How genetic testing and biomarkers can help tailor heart disease treatment to each patient.",
    tags: ["Precision Medicine", "Cardiology", "Genomics"],
    year: 2023,
  },
  {
    id: "pub-6",
    title: "CAR-T Cell Therapy: From Bench to Bedside and Beyond",
    authors: ["June, C.H.", "O'Connor, R.S.", "Kawalekar, O.U."],
    abstract: "Chimeric antigen receptor (CAR) T-cell therapy represents a paradigm shift in cancer treatment. This review traces the development of CAR-T technology, discusses current clinical applications in hematologic malignancies, and explores emerging strategies for solid tumors.",
    summary: "The evolution of CAR-T therapy from laboratory research to treating blood cancers and future applications.",
    tags: ["CAR-T", "Cell Therapy", "Immunotherapy"],
    year: 2024,
  },
  {
    id: "pub-7",
    title: "Liquid Biopsy for Cancer Detection and Monitoring",
    authors: ["Wan, J.C.", "Massie, C.", "Caldas, C."],
    abstract: "Circulating tumor DNA (ctDNA) and other blood-based biomarkers offer minimally invasive alternatives for cancer detection and monitoring. This article reviews the biology of cell-free DNA, clinical applications of liquid biopsy, and future directions in precision oncology.",
    summary: "Blood tests that can detect cancer early and monitor treatment response without surgery.",
    tags: ["Liquid Biopsy", "ctDNA", "Early Detection"],
    year: 2024,
  },
  {
    id: "pub-8",
    title: "The Tumor Microenvironment: Implications for Cancer Therapy",
    authors: ["Hinshaw, D.C.", "Shevde, L.A."],
    abstract: "The tumor microenvironment plays crucial roles in cancer progression, metastasis, and therapy resistance. This review examines cellular and molecular components of the tumor microenvironment, their interactions with cancer cells, and therapeutic strategies targeting this ecosystem.",
    summary: "Understanding the environment around tumors and how targeting it can improve cancer treatment.",
    tags: ["Tumor Microenvironment", "Cancer Biology", "Therapeutics"],
    year: 2023,
  },
  {
    id: "pub-9",
    title: "mRNA Vaccines: A New Era in Vaccinology and Beyond",
    authors: ["Pardi, N.", "Hogan, M.J.", "Weissman, D."],
    abstract: "The success of mRNA COVID-19 vaccines has validated this platform technology. This article discusses the history, mechanisms, and advantages of mRNA vaccines, explores applications in infectious diseases and cancer immunotherapy, and addresses manufacturing and delivery challenges.",
    summary: "How mRNA vaccine technology works and its potential beyond COVID-19, including cancer treatment.",
    tags: ["mRNA", "Vaccines", "Immunology"],
    year: 2024,
  },
  {
    id: "pub-10",
    title: "Single-Cell Sequencing in Cancer Research",
    authors: ["Navin, N.E.", "Chen, K."],
    abstract: "Single-cell technologies have revealed unprecedented tumor heterogeneity and evolution. This review covers single-cell RNA, DNA, and multi-omics sequencing approaches, their applications in understanding tumor biology, and implications for precision medicine.",
    summary: "New technologies that analyze individual cancer cells to understand tumor diversity and evolution.",
    tags: ["Single-Cell", "Genomics", "Cancer Research"],
    year: 2024,
  },
  {
    id: "pub-11",
    title: "Epigenetic Modifications in Cancer Development and Therapy",
    authors: ["Feinberg, A.P.", "Koldobskiy, M.A.", "Gondor, A."],
    abstract: "Epigenetic alterations are fundamental to cancer development. This article explores DNA methylation, histone modifications, and chromatin remodeling in cancer, discusses epigenetic biomarkers, and reviews therapeutic strategies targeting the epigenome.",
    summary: "How chemical modifications to DNA affect cancer development and can be targeted for treatment.",
    tags: ["Epigenetics", "Cancer", "Therapeutics"],
    year: 2023,
  },
  {
    id: "pub-12",
    title: "Antibody-Drug Conjugates: Design, Development, and Clinical Impact",
    authors: ["Drago, J.Z.", "Modi, S.", "Chandarlapaty, S."],
    abstract: "Antibody-drug conjugates (ADCs) combine the targeting specificity of antibodies with cytotoxic payloads. This review discusses ADC design principles, mechanisms of action, clinical successes in breast cancer and beyond, and strategies to overcome resistance.",
    summary: "Precision weapons that deliver chemotherapy directly to cancer cells using antibodies as targeting systems.",
    tags: ["ADC", "Targeted Therapy", "Breast Cancer"],
    year: 2024,
  },
  {
    id: "pub-13",
    title: "Metabolic Reprogramming in Cancer: Therapeutic Opportunities",
    authors: ["Vander Heiden, M.G.", "DeBerardinis, R.J."],
    abstract: "Cancer cells exhibit altered metabolism to support rapid proliferation. This article examines metabolic vulnerabilities in cancer, discusses biomarkers for metabolic profiling, and explores therapeutic strategies targeting cancer metabolism.",
    summary: "How cancer cells change their metabolism and new treatment approaches that exploit these changes.",
    tags: ["Cancer Metabolism", "Therapeutics", "Precision Medicine"],
    year: 2024,
  },
  {
    id: "pub-14",
    title: "Radiation Therapy in the Era of Immunotherapy",
    authors: ["Formenti, S.C.", "Demaria, S."],
    abstract: "Radiation therapy can modulate the immune system and enhance immunotherapy efficacy. This review explores mechanisms of radiation-induced immune activation, discusses optimal combinations with immunotherapy, and presents clinical trial results.",
    summary: "How radiation treatment can boost the immune system and work better when combined with immunotherapy.",
    tags: ["Radiation", "Immunotherapy", "Combination Therapy"],
    year: 2023,
  },
  {
    id: "pub-15",
    title: "Organoid Models in Cancer Research and Drug Development",
    authors: ["Drost, J.", "Clevers, H."],
    abstract: "Patient-derived organoids recapitulate tumor architecture and heterogeneity. This article reviews organoid culture methods, applications in studying cancer biology and drug responses, and their role in precision medicine and drug development.",
    summary: "Growing mini-tumors in the lab to test treatments and understand cancer biology.",
    tags: ["Organoids", "Drug Development", "Precision Medicine"],
    year: 2024,
  },
  {
    id: "pub-16",
    title: "Synthetic Lethality: Exploiting Genetic Dependencies in Cancer",
    authors: ["Lord, C.J.", "Ashworth, A."],
    abstract: "Synthetic lethality occurs when loss of two genes is lethal but loss of either alone is not. This review examines PARP inhibitors as a proof-of-concept, discusses screening approaches to identify synthetic lethal interactions, and explores future therapeutic applications.",
    summary: "Finding and targeting genetic weaknesses in cancer cells, like PARP inhibitors for BRCA mutations.",
    tags: ["Synthetic Lethality", "PARP Inhibitors", "Targeted Therapy"],
    year: 2023,
  },
  {
    id: "pub-17",
    title: "The Gut Microbiome and Cancer Immunotherapy Response",
    authors: ["Routy, B.", "Gopalakrishnan, V.", "Daillère, R."],
    abstract: "Emerging evidence links gut microbiome composition to immunotherapy outcomes. This article reviews mechanisms by which microbiota influence anti-tumor immunity, discusses microbiome biomarkers for therapy response, and explores interventions to modulate the microbiome.",
    summary: "How gut bacteria affect whether immunotherapy works and strategies to improve treatment response.",
    tags: ["Microbiome", "Immunotherapy", "Biomarkers"],
    year: 2024,
  },
  {
    id: "pub-18",
    title: "Circadian Rhythms and Cancer: Timing Matters",
    authors: ["Sulli, G.", "Manoogian, E.N.", "Taub, P.R."],
    abstract: "Circadian disruption increases cancer risk and affects treatment outcomes. This review examines links between circadian rhythms and cancer development, discusses chronotherapy approaches, and explores circadian biomarkers for precision timing of treatments.",
    summary: "How body clocks affect cancer development and why timing of treatment matters.",
    tags: ["Circadian Rhythm", "Chronotherapy", "Cancer Biology"],
    year: 2023,
  },
  {
    id: "pub-19",
    title: "Exosomes in Cancer: From Biomarkers to Therapeutics",
    authors: ["Kalluri, R.", "LeBleu, V.S."],
    abstract: "Extracellular vesicles play roles in cancer progression and resistance. This article reviews exosome biology, their roles in tumor-stroma communication, potential as biomarkers, and therapeutic applications including drug delivery.",
    summary: "Tiny packages released by cells that spread cancer and could be used for diagnosis and treatment.",
    tags: ["Exosomes", "Biomarkers", "Drug Delivery"],
    year: 2024,
  },
  {
    id: "pub-20",
    title: "Cancer Stem Cells: Biology and Therapeutic Implications",
    authors: ["Batlle, E.", "Clevers, H."],
    abstract: "Cancer stem cells drive tumor initiation, metastasis, and recurrence. This review examines cancer stem cell identification, their role in therapy resistance, and strategies to target stem-like populations in various cancer types.",
    summary: "Understanding cancer stem cells and developing treatments that target these resilient tumor-starting cells.",
    tags: ["Cancer Stem Cells", "Drug Resistance", "Therapeutics"],
    year: 2024,
  },
  {
    id: "pub-21",
    title: "Nanomedicine in Cancer Therapy: Opportunities and Challenges",
    authors: ["Shi, J.", "Kantoff, P.W.", "Wooster, R."],
    abstract: "Nanoparticles offer enhanced drug delivery and imaging capabilities. This article discusses nanoparticle design, targeting strategies, clinical translation of nanomedicines, and challenges in manufacturing and regulatory approval.",
    summary: "Using tiny particles to deliver drugs more effectively and image tumors better.",
    tags: ["Nanomedicine", "Drug Delivery", "Imaging"],
    year: 2023,
  },
  {
    id: "pub-22",
    title: "Immune Checkpoint Inhibitors: Mechanisms and Resistance",
    authors: ["Ribas, A.", "Wolchok, J.D."],
    abstract: "Immune checkpoint inhibitors have transformed cancer treatment. This review covers mechanisms of checkpoint blockade, response biomarkers, primary and acquired resistance mechanisms, and strategies to enhance efficacy.",
    summary: "How drugs that release the brakes on the immune system work and why they don't work for everyone.",
    tags: ["Checkpoint Inhibitors", "Immunotherapy", "Resistance"],
    year: 2024,
  },
  {
    id: "pub-23",
    title: "3D Bioprinting for Cancer Research and Tissue Engineering",
    authors: ["Murphy, S.V.", "Atala, A."],
    abstract: "3D bioprinting creates complex tissue models for research and potential therapeutic applications. This article reviews bioprinting technologies, applications in cancer modeling, drug testing, and future prospects in regenerative medicine.",
    summary: "Printing 3D tissue models to study cancer and test new treatments.",
    tags: ["Bioprinting", "Tissue Engineering", "Cancer Models"],
    year: 2024,
  },
  {
    id: "pub-24",
    title: "Ferroptosis: A Novel Cell Death Pathway in Cancer Therapy",
    authors: ["Dixon, S.J.", "Stockwell, B.R."],
    abstract: "Ferroptosis is an iron-dependent form of regulated cell death. This review examines ferroptosis mechanisms, its role in cancer biology, therapeutic strategies to induce ferroptosis in cancer cells, and biomarkers for ferroptosis-based therapies.",
    summary: "A newly discovered way cells die that could be triggered to kill cancer cells.",
    tags: ["Ferroptosis", "Cell Death", "Cancer Therapy"],
    year: 2023,
  },
  {
    id: "pub-25",
    title: "Tumor Evolution and Clonal Dynamics During Treatment",
    authors: ["Gerlinger, M.", "Swanton, C."],
    abstract: "Tumors evolve under selective pressure from therapy. This article discusses methods to track clonal evolution, mechanisms of treatment-induced selection, implications for resistance, and strategies for evolutionary therapy.",
    summary: "How tumors change over time during treatment and what this means for therapy strategies.",
    tags: ["Tumor Evolution", "Clonal Dynamics", "Resistance"],
    year: 2024,
  },
  {
    id: "pub-26",
    title: "The Role of Inflammation in Cancer Development",
    authors: ["Grivennikov, S.I.", "Greten, F.R.", "Karin, M."],
    abstract: "Chronic inflammation promotes cancer development and progression. This review examines inflammatory pathways in carcinogenesis, links between inflammatory conditions and cancer risk, and anti-inflammatory strategies for cancer prevention and treatment.",
    summary: "How chronic inflammation causes cancer and treatments that reduce inflammation to prevent cancer.",
    tags: ["Inflammation", "Cancer Prevention", "Carcinogenesis"],
    year: 2023,
  },
  {
    id: "pub-27",
    title: "Proteomics in Precision Oncology",
    authors: ["Mertins, P.", "Carr, S.A."],
    abstract: "Proteomic analysis complements genomics in cancer characterization. This article reviews proteomic technologies, applications in biomarker discovery, drug target identification, and integration with other omics data for precision medicine.",
    summary: "Analyzing proteins in tumors to better understand cancer and find new treatment targets.",
    tags: ["Proteomics", "Biomarkers", "Precision Oncology"],
    year: 2024,
  },
  {
    id: "pub-28",
    title: "Senescence in Cancer: Friend or Foe?",
    authors: ["Schmitt, C.A.", "Wang, B.", "Demaria, M."],
    abstract: "Cellular senescence has dual roles in cancer. This review discusses oncogene-induced senescence as a tumor suppressor mechanism, therapy-induced senescence, and the senescence-associated secretory phenotype (SASP) in tumor progression and treatment.",
    summary: "When cells stop dividing it can prevent or promote cancer depending on the context.",
    tags: ["Senescence", "Tumor Suppression", "SASP"],
    year: 2024,
  },
  {
    id: "pub-29",
    title: "Spatial Transcriptomics: Mapping Gene Expression in Tumors",
    authors: ["Marx, V."],
    abstract: "Spatial transcriptomics preserves tissue architecture while measuring gene expression. This article reviews spatial transcriptomics technologies, applications in mapping tumor heterogeneity, and insights into tumor-immune interactions.",
    summary: "New technology that shows where genes are active in tumors while keeping tissue structure intact.",
    tags: ["Spatial Transcriptomics", "Tumor Heterogeneity", "Technology"],
    year: 2024,
  },
  {
    id: "pub-30",
    title: "Targeting Cancer Metabolism: Clinical Translation and Challenges",
    authors: ["Luengo, A.", "Gui, D.Y.", "Vander Heiden, M.G."],
    abstract: "Metabolic dependencies offer therapeutic opportunities. This review examines clinical trials targeting cancer metabolism, discusses successes and failures, identifies promising metabolic targets, and proposes strategies to improve clinical translation.",
    summary: "Efforts to turn discoveries about cancer metabolism into actual treatments and lessons learned.",
    tags: ["Cancer Metabolism", "Clinical Trials", "Drug Development"],
    year: 2023,
  },
];

// Mock Forum Posts Data
export const mockForums: ForumPost[] = [
  {
    id: "forum-1",
    title: "Looking for collaborators on cancer immunotherapy research",
    category: "Collaboration Opportunities",
    content: "I'm leading a research group focused on CAR-T cell therapy for solid tumors. We're looking for collaborators with expertise in tumor microenvironment analysis. Interested in sharing techniques and data.",
    author: "Dr. Sarah Chen",
    tags: ["Collaboration", "CAR-T", "Cancer"],
    replies: 12,
    views: 234,
    timestamp: new Date("2024-01-15"),
  },
  {
    id: "forum-2",
    title: "What are the latest developments in Alzheimer's biomarkers?",
    category: "Research Questions",
    content: "Can anyone share insights on the most promising biomarkers for early Alzheimer's detection? Particularly interested in blood-based markers vs. CSF analysis.",
    author: "Dr. Yuki Tanaka",
    tags: ["Alzheimer's", "Biomarkers", "Diagnostics"],
    replies: 8,
    views: 156,
    timestamp: new Date("2024-01-14"),
  },
  {
    id: "forum-3",
    title: "Experience with CRISPR clinical trials - seeking advice",
    category: "Clinical Trials",
    content: "We're preparing to initiate a Phase I CRISPR trial for a rare genetic disorder. Would appreciate any advice from those who've navigated the regulatory process for gene editing trials.",
    author: "Dr. Maria Rodriguez",
    tags: ["CRISPR", "Clinical Trials", "Regulations"],
    replies: 15,
    views: 289,
    timestamp: new Date("2024-01-13"),
  },
  {
    id: "forum-4",
    title: "My experience with immunotherapy side effects",
    category: "Patient Experience",
    content: "I've been on checkpoint inhibitor therapy for melanoma for 6 months. Happy to share my experience with managing side effects and what helped me through the journey.",
    author: "Patient Advocate",
    tags: ["Immunotherapy", "Side Effects", "Patient Support"],
    replies: 24,
    views: 412,
    timestamp: new Date("2024-01-12"),
  },
  {
    id: "forum-5",
    title: "Best practices for patient recruitment in rare disease trials",
    category: "Clinical Trials",
    content: "We're struggling with recruitment for our rare disease trial. What strategies have worked for others? Any recommended patient advocacy groups or platforms?",
    author: "Prof. David Kim",
    tags: ["Recruitment", "Rare Disease", "Clinical Trials"],
    replies: 19,
    views: 301,
    timestamp: new Date("2024-01-11"),
  },
  {
    id: "forum-6",
    title: "Machine learning approaches for predicting treatment response",
    category: "Research Questions",
    content: "Exploring ML models to predict immunotherapy response. What features and algorithms have shown promise in your work?",
    author: "Dr. Robert Zhang",
    tags: ["Machine Learning", "Predictive Models", "Immunotherapy"],
    replies: 22,
    views: 387,
    timestamp: new Date("2024-01-10"),
  },
  {
    id: "forum-7",
    title: "Managing treatment costs - patient perspective",
    category: "Patient Experience",
    content: "The financial burden of cancer treatment is overwhelming. Looking for advice on navigating insurance, assistance programs, and managing costs.",
    author: "Cancer Patient",
    tags: ["Financial", "Patient Support", "Insurance"],
    replies: 31,
    views: 523,
    timestamp: new Date("2024-01-09"),
  },
  {
    id: "forum-8",
    title: "Organoid models vs. animal models for drug testing",
    category: "Research Questions",
    content: "We're evaluating organoids as an alternative to animal models. What have been your experiences with predictive accuracy and translational success?",
    author: "Prof. Sophie Dubois",
    tags: ["Organoids", "Drug Testing", "Research Methods"],
    replies: 17,
    views: 298,
    timestamp: new Date("2024-01-08"),
  },
  {
    id: "forum-9",
    title: "Fertility preservation options before cancer treatment",
    category: "Treatment Options",
    content: "Starting chemotherapy soon and want to preserve fertility. What options are available and what should I consider?",
    author: "Young Patient",
    tags: ["Fertility", "Chemotherapy", "Quality of Life"],
    replies: 14,
    views: 267,
    timestamp: new Date("2024-01-07"),
  },
  {
    id: "forum-10",
    title: "Multi-omics integration in precision oncology",
    category: "Research Questions",
    content: "Seeking recommendations for tools and approaches to integrate genomic, transcriptomic, and proteomic data for treatment decisions.",
    author: "Dr. Jennifer Park",
    tags: ["Multi-omics", "Precision Medicine", "Bioinformatics"],
    replies: 11,
    views: 214,
    timestamp: new Date("2024-01-06"),
  },
  {
    id: "forum-11",
    title: "Survivorship care plans - what should be included?",
    category: "General Discussion",
    content: "Developing survivorship care plans for our patients. What elements do you include? How do you address long-term effects?",
    author: "Dr. Lisa Müller",
    tags: ["Survivorship", "Care Plans", "Follow-up"],
    replies: 19,
    views: 342,
    timestamp: new Date("2024-01-05"),
  },
  {
    id: "forum-12",
    title: "Clinical trial transparency and data sharing",
    category: "General Discussion",
    content: "What are your thoughts on mandatory data sharing from clinical trials? Balancing transparency with competitive concerns.",
    author: "Prof. Michael Anderson",
    tags: ["Clinical Trials", "Data Sharing", "Ethics"],
    replies: 27,
    views: 445,
    timestamp: new Date("2024-01-04"),
  },
  {
    id: "forum-13",
    title: "Palliative care integration in oncology",
    category: "Treatment Options",
    content: "When is the right time to introduce palliative care? How do you have these conversations with patients and families?",
    author: "Dr. Emma Williams",
    tags: ["Palliative Care", "Communication", "Quality of Life"],
    replies: 23,
    views: 389,
    timestamp: new Date("2024-01-03"),
  },
  {
    id: "forum-14",
    title: "Liquid biopsy implementation in clinical practice",
    category: "Research Questions",
    content: "We're implementing ctDNA testing. What platforms are you using? How are you incorporating results into treatment decisions?",
    author: "Dr. Ahmed Hassan",
    tags: ["Liquid Biopsy", "ctDNA", "Clinical Practice"],
    replies: 16,
    views: 312,
    timestamp: new Date("2024-01-02"),
  },
  {
    id: "forum-15",
    title: "Dealing with scanxiety - tips and support",
    category: "Patient Experience",
    content: "The anxiety before scans is overwhelming. How do other patients cope? Any tips for managing the waiting period?",
    author: "Cancer Survivor",
    tags: ["Scanxiety", "Mental Health", "Coping"],
    replies: 38,
    views: 621,
    timestamp: new Date("2024-01-01"),
  },
  {
    id: "forum-16",
    title: "Funding opportunities for early career researchers",
    category: "Collaboration Opportunities",
    content: "Compiling a list of funding sources for junior investigators in oncology. Please share grants and fellowships you've found helpful.",
    author: "Dr. Raj Patel",
    tags: ["Funding", "Early Career", "Research"],
    replies: 29,
    views: 487,
    timestamp: new Date("2023-12-30"),
  },
  {
    id: "forum-17",
    title: "Exercise during cancer treatment - evidence and protocols",
    category: "Treatment Options",
    content: "Looking for evidence-based exercise protocols for patients undergoing active treatment. What's working in your practice?",
    author: "Prof. Hans Schmidt",
    tags: ["Exercise", "Treatment", "Quality of Life"],
    replies: 21,
    views: 356,
    timestamp: new Date("2023-12-29"),
  },
  {
    id: "forum-18",
    title: "Microbiome testing before immunotherapy - worth it?",
    category: "Research Questions",
    content: "Considering baseline microbiome assessment for immunotherapy patients. What tests are you using? Do results influence treatment?",
    author: "Dr. Carlos Mendes",
    tags: ["Microbiome", "Immunotherapy", "Testing"],
    replies: 13,
    views: 276,
    timestamp: new Date("2023-12-28"),
  },
  {
    id: "forum-19",
    title: "Second opinions - when and how to seek them",
    category: "Patient Experience",
    content: "When should patients seek second opinions? How do you approach this with your oncologist without offending them?",
    author: "Concerned Patient",
    tags: ["Second Opinion", "Patient Rights", "Decision Making"],
    replies: 26,
    views: 498,
    timestamp: new Date("2023-12-27"),
  },
  {
    id: "forum-20",
    title: "AI in radiology - impact on cancer detection",
    category: "General Discussion",
    content: "AI tools are increasingly used in imaging. What's your experience with AI-assisted detection? Improvements in accuracy?",
    author: "Dr. Kenji Yamamoto",
    tags: ["AI", "Radiology", "Detection"],
    replies: 18,
    views: 334,
    timestamp: new Date("2023-12-26"),
  },
  {
    id: "forum-21",
    title: "Pediatric oncology collaboration network",
    category: "Collaboration Opportunities",
    content: "Establishing an international network for pediatric oncology research. Interested in joining? Looking for centers to participate.",
    author: "Prof. Sophie Dubois",
    tags: ["Pediatric", "Network", "Collaboration"],
    replies: 24,
    views: 412,
    timestamp: new Date("2023-12-25"),
  },
  {
    id: "forum-22",
    title: "Complementary therapies - patient experiences",
    category: "Treatment Options",
    content: "Has anyone tried acupuncture, meditation, or other complementary approaches during cancer treatment? What helped?",
    author: "Holistic Patient",
    tags: ["Complementary", "Holistic", "Patient Experience"],
    replies: 34,
    views: 589,
    timestamp: new Date("2023-12-24"),
  },
  {
    id: "forum-23",
    title: "Tumor board presentations - best practices",
    category: "General Discussion",
    content: "Tips for effective tumor board presentations? How do you present complex cases concisely?",
    author: "Dr. Fatima Al-Rashid",
    tags: ["Tumor Board", "Presentation", "Best Practices"],
    replies: 15,
    views: 287,
    timestamp: new Date("2023-12-23"),
  },
  {
    id: "forum-24",
    title: "Resistance mechanisms to targeted therapy",
    category: "Research Questions",
    content: "Studying acquired resistance to EGFR inhibitors. What mechanisms are you seeing? Strategies to overcome resistance?",
    author: "Dr. Thomas van der Berg",
    tags: ["Resistance", "Targeted Therapy", "EGFR"],
    replies: 20,
    views: 367,
    timestamp: new Date("2023-12-22"),
  },
  {
    id: "forum-25",
    title: "Clinical trial participation - patient decision making",
    category: "Clinical Trials",
    content: "What factors influence your decision to join a clinical trial? What information helped you decide?",
    author: "Trial Participant",
    tags: ["Clinical Trials", "Decision Making", "Patient Perspective"],
    replies: 28,
    views: 456,
    timestamp: new Date("2023-12-21"),
  },
  {
    id: "forum-26",
    title: "Telemedicine in oncology post-pandemic",
    category: "General Discussion",
    content: "How are you integrating telemedicine into oncology care? What works well remotely vs. needs in-person visits?",
    author: "Dr. Aisha Nkomo",
    tags: ["Telemedicine", "Virtual Care", "COVID"],
    replies: 22,
    views: 398,
    timestamp: new Date("2023-12-20"),
  },
  {
    id: "forum-27",
    title: "Caregiving challenges and support",
    category: "Patient Experience",
    content: "I'm the primary caregiver for my spouse with cancer. The emotional and physical toll is immense. How do other caregivers cope?",
    author: "Dedicated Caregiver",
    tags: ["Caregiving", "Support", "Mental Health"],
    replies: 41,
    views: 678,
    timestamp: new Date("2023-12-19"),
  },
  {
    id: "forum-28",
    title: "Biomarker-driven trial design",
    category: "Clinical Trials",
    content: "Designing a basket trial based on molecular markers. What are key considerations for biomarker-driven studies?",
    author: "Prof. Dimitri Volkov",
    tags: ["Biomarkers", "Trial Design", "Precision Medicine"],
    replies: 14,
    views: 259,
    timestamp: new Date("2023-12-18"),
  },
  {
    id: "forum-29",
    title: "Side effect management - practical tips",
    category: "Treatment Options",
    content: "Oncologists and patients: what are your best practical tips for managing common side effects like nausea, fatigue, neuropathy?",
    author: "Dr. Isabella Romano",
    tags: ["Side Effects", "Management", "Practical Tips"],
    replies: 36,
    views: 612,
    timestamp: new Date("2023-12-17"),
  },
  {
    id: "forum-30",
    title: "Grant writing workshop collaboration",
    category: "Collaboration Opportunities",
    content: "Organizing a virtual grant writing workshop for junior faculty. Looking for experienced mentors to participate. Interested?",
    author: "Dr. Priya Sharma",
    tags: ["Grant Writing", "Workshop", "Mentorship"],
    replies: 17,
    views: 324,
    timestamp: new Date("2023-12-16"),
  },
];

// API Functions
export async function getExperts(): Promise<Expert[]> {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockExperts;
}

export async function getTrials(): Promise<ClinicalTrial[]> {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockTrials;
}

export async function getPublications(): Promise<Publication[]> {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockPublications;
}

export async function getForums(): Promise<ForumPost[]> {
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockForums;
}

export interface Recommendation {
  type: "expert" | "trial" | "publication";
  item: Expert | ClinicalTrial | Publication;
  reason: string;
}

export async function getRecommendations(userType: "patient" | "researcher"): Promise<Recommendation[]> {
  await new Promise(resolve => setTimeout(resolve, 500));
  
  if (userType === "patient") {
    return [
      {
        type: "expert",
        item: mockExperts[0],
        reason: "Top-rated oncology specialist with expertise in your condition",
      },
      {
        type: "trial",
        item: mockTrials[0],
        reason: "Currently recruiting for a trial matching your profile",
      },
      {
        type: "publication",
        item: mockPublications[0],
        reason: "Latest research relevant to your condition",
      },
    ];
  } else {
    return [
      {
        type: "publication",
        item: mockPublications[1],
        reason: "Highly cited paper in your field of research",
      },
      {
        type: "expert",
        item: mockExperts[1],
        reason: "Potential collaborator with complementary expertise",
      },
      {
        type: "trial",
        item: mockTrials[1],
        reason: "Trial seeking researchers with your background",
      },
    ];
  }
}

// n8n Webhook Integration
export async function sendToN8n(eventType: string, payload: any) {
  try {
    const response = await fetch("http://localhost:5678/webhook-test/ca5d7c57-8e03-4009-ba66-c5d493488908", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        eventType,
        payload,
        timestamp: new Date().toISOString(),
      }),
    });
    
    if (!response.ok) {
      console.error("n8n webhook error:", response.statusText);
    }
  } catch (error) {
    console.error("Error sending to n8n:", error);
  }
}

// OpenAI Integration for Chatbot
export async function sendChatMessage(message: string, conversationHistory: Array<{ role: string; content: string }>) {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${import.meta.env.VITE_OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4",
      messages: [
        {
          role: "system",
          content: "You are CuraLink AI, a helpful medical research assistant. Help users find experts, clinical trials, and publications. Provide clear summaries and actionable next steps. Be empathetic with patients and professional with researchers.",
        },
        ...conversationHistory,
        {
          role: "user",
          content: message,
        },
      ],
      stream: true,
    }),
  });

  return response;
}
